### ISSUE TITLE
运行不显示甘特图

### ISSUE THREAD

**Issue by lancyJD** [lee576/vue-gantt#1]
![image](https://user-images.githubusercontent.com/11610702/174990525-6be7aa44-d1ff-4ff6-bae0-a7582f3f3799.png)

**Comment by lee576** [comment]
数据源是我写的Json样例数据，实际开发的时候应该是ajax从后端取来，时间范围在3月份，选择的时间范围对了，甘特图才能显示

**Comment by lancyJD** [comment]
谢楼主，还会继续更新吗？  会不会改成cavens呢？

**Comment by lee576** [comment]
精力有限，近期不会
